#SPDX-License-Identifier: MIT-0
---
# vars file for roles/django

django_manage_py: "{{ app_directory }}/manage.py"
django_python: "{{ venv_directory }}/bin/python"
django_env_file: "{{ app_directory }}/.env"
django_settings_module: inventory_system.settings